version: '3.8'

services:
  backend:
    image: nagulesh123/busbooking-backend:1.0
    build: .
    ports:
      - "5001:5001"
    env_file: 
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    

volumes:
  mongodb_data:
